### ISSUE TITLE
Request: Update for Bootstrap 4 support

### ISSUE THREAD

**Issue by beargie** [dabernathy89/vue-query-builder#24]
https://getbootstrap.com/docs/4.0/migration/

Existing rendered component objects are not compatible with v4 bootstrap. EG buttons with btn-default class will render as plain white buttons since it was changed to btn-secondary in v4.

**Comment by dabernathy89** [comment]
Thanks @beargie. There actually was a recent pull request to add BS4 support. I wanted to merge, but I don't want to lose Bootstrap 3 support and i'm not ready to move the component out of the `0.x` range yet.

I'd like to refactor the component using scoped slots so that consumers can provide whatever HTML structure & CSS classes they want. Just had a baby a few weeks ago, so I haven't had a chance to implement that yet. Hope to ASAP.

**Comment by dabernathy89** [comment]
Going to go ahead and close this for now. I hope to have a version out soon which will make it easier for users to use whatever CSS framework they'd like.
