### ISSUE TITLE
How can we modity the UI?

### ISSUE THREAD

**Issue by jelordreygulle** [dabernathy89/vue-query-builder#35]
Hi, Good day . As far as a i know the build was installed and then imported to the project "import VueQueryBuilder from "vue-query-builder";" but i can't seem to locate where to changed it.As you can see in the screenshot, by the way I am using the sample project you put on code sandbox which is this link (https://codesandbox.io/s/r0r7jjjnko?from-embed). I just wanted to know how can we modify its interface as you can see on the screenshot. For example i wanted to changed that vegetable textfield to a select option where data comes from an API or change the button or add more to the UI. A reply would be a great help , Thank You.
![screen shot 2018-10-10 at 2 56 08 pm](https://user-images.githubusercontent.com/14964168/46718706-9dd9dd00-cc9e-11e8-8976-989ec19a8425.png)

**Comment by dabernathy89** [comment]
Hey @jelordreygulle - right now there is not a lot of customization available. I'm working on a refactor that will involve slots and potentially some other ways to replace/insert your own HTML content.

However, what you're talking about should be doable; it's the primary purpose of the component :)

Since this issues board is primarily meant for bug reports, rather than support requests, I'm going to go ahead and close this issue and encourage you to check out the documentation here on `rules`, which shows you how to create different rule types that let you fill in values using a variety of inputs, including dropdowns, checkboxes, radios, etc:

https://dabernathy89.github.io/vue-query-builder/configuration.html#rules
