### ISSUE TITLE
How to get the output JSON?

### ISSUE THREAD

**Issue by ytl18** [dabernathy89/vue-query-builder#50]

**Comment by dabernathy89** [comment]
Hey @ytl18 - the component uses `v-model` so that you can pass through your own object (either empty or with an existing query) and the component will update it as the user interacts with the form.

See details here:

https://dabernathy89.github.io/vue-query-builder/configuration.html#v-model

While it's listed as `optional`, realistically you will always want to use `v-model`.

**Comment by ytl18** [comment]
> Hey @ytl18 - the component uses `v-model` so that you can pass through your own object (either empty or with an existing query) and the component will update it as the user interacts with the form.
> 
> See details here:
> 
> https://dabernathy89.github.io/vue-query-builder/configuration.html#v-model
> 
> While it's listed as `optional`, realistically you will always want to use `v-model`.

Hi @dabernathy89 
Thanks very much for your replying. I understand.
